### ISSUE TITLE
TypeError: Cannot read property 'lockToPortrait' of undefined

### ISSUE THREAD

**Issue by xstable** [mostafa/react-native-fullscreen-video#10]
Got this error after installing and running FullScreenVideo.

Part of my package.json:
```
    "react": "16.3.1",
    "react-devtools": "^3.2.1",
    "react-native": "^0.55.3",
    "react-native-collapsible": "^0.11.2",
    "react-native-fcm": "^15.0.2",
    "react-native-fullscreen-video": "^0.0.9",
```

**Comment by mostafa** [comment]
It's about a function of [react-native-orientation](https://github.com/yamill/react-native-orientation) package. Perhaps you haven't linked the package with your code.
