### ISSUE TITLE
Just installed this library and get an error: undefined is not an object (evaluating 'Orientation.lockToPortrait')

### ISSUE THREAD

**Issue by Hannibal2** [mostafa/react-native-fullscreen-video#13]
Just installed this library and get an error: undefined is not an object (evaluating 'Orientation.lockToPortrait'). After that I installed and configure another library (Orientation), but got next error: undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants'). Any idea?

**Comment by HideOnBushTuT** [comment]
i got the same error too.

**Comment by edwardxuluc** [comment]
me too

**Comment by Senocico** [comment]
the same

**Comment by Hannibal2** [comment]
react-native-video and orienation libraries must be installed. So actually you need to istall 3 libraries (video, orientation and this one)
