### ISSUE TITLE
null is not an object (evaluating  'Orientation.lockToPortait')

### ISSUE THREAD

**Issue by elrhomariyounes** [mostafa/react-native-fullscreen-video#15]
### To Reproduce
* In App.js
```javascript
import FullscreenVideo from 'react-native-fullscreen-video';

render(){
        return (
              <View style={{flex: 1}}>
                  <FullscreenVideo src=require('Assets')
                       controls/>
              </View>
         )
}
```
### More
* node version
```bash
$ node -v
v10.17.0

$ npm -v
6.11.3
```
* react-native : 0.62.2
* react-native-fullscreen-video : 0.0.9

**Comment by DTX-Elliot** [comment]
I'm getting this issue too, did you manage to fix it?

**Comment by mostafa** [comment]
Hi @elrhomariyounes and @DTX-Elliot,

have you added the depedency to your projects' `package.json`?
`"react-native-orientation": "^3.1.3"`

After almost 3 years I've tested the simple example, and it works like a charm with Android SDK version 30 and RN v0.52.0. I'll try to update the RN to see what happens.

**Comment by DTX-Elliot** [comment]
Hi, yes I have although the example is now working. Not sure what it was but after a restart it's fixed. Thanks anyway!
