### ISSUE TITLE
Orientation.lockToPortrait error

### ISSUE THREAD

**Issue by eseQ** [mostafa/react-native-fullscreen-video#4]
Hello. 
I got that error: `undefined is not an object (evaluating 'Orientation.lockToPortrait')`

**Comment by eseQ** [comment]
Ok, i fix in after [configurate](https://github.com/yamill/react-native-orientation#configuration), but now have new error: `undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants')`

**Comment by eseQ** [comment]
I just setup this again without `react-native-fullscreen-video`

**Comment by Hannibal2** [comment]
@eseQ I have the same issue now.
And I don't understand the solution. I need to configure React Native Orientation? and what I should do after it?

**Comment by eseQ** [comment]
@Hannibal2 yeah, try reconfigure by following instruction. Sorry but i can`t remember what i did.

**Comment by Hannibal2** [comment]
@eseQ I already fixed it. Follow next steps and everything will work great.
 Steps: 
1. Install and configure react-native-video;
2. Install and configure react-native-orientation;
3. Install and configure react-native-fullscreen-video;
