### ISSUE TITLE
Nothing appears

### ISSUE THREAD

**Issue by ShariqMush** [mostafa/react-native-fullscreen-video#5]
I tried to run the example but nothing appears, sometimes the screen turns black but does not display anything

**Comment by mostafa** [comment]
I'll check it out!

**Comment by mostafa** [comment]
Fixed it. I was using master branch of react-native-orientation instead of stable version (2.0.0).

**Comment by ShariqMush** [comment]
Thank you! Love this project hope to contribute sometime, I'm trying to integrate controls with this but since I'm a beginner it's a bit tough for me bit I'll try to do it😀
