### ISSUE TITLE
Non-flux example, it seems react-native-lock-orientation is requirement

### ISSUE THREAD

**Issue by Noitidart** [mostafa/react-native-fullscreen-video#6]
Hi there,
May you please show a non-flux example.

Also if possible a gif of this in action would be awesome.

**Comment by mostafa** [comment]
Hi,
I'll update it soon and will include a non-flux example.
Gif is also a good idea, I'll make one!

**Comment by Noitidart** [comment]
Thank you sir very much for your awesome work and willingness to help me! :)

**Comment by mostafa** [comment]
Added GIF demo.

**Comment by Noitidart** [comment]
Thanks the vid looks great. I don't use flux, we're all redux for the past 2 years, so I was never able to install this. So the vid is much appreciated!

**Comment by mostafa** [comment]
I tried to make an example using react-router but after hours of trying, I couldn't keep up with the ever-changing API of react-native with so much breaking changes.
FYI, the component does not work/integrate with react-native-router-flux. Using react-native-router-flux is just an example of how to use this component. This means that you can use it with any other navigation and state container package.

**Comment by Noitidart** [comment]
Thanks very much for that effort. You're totally correct no one use react-router in React Native. I made that mistake as well for a few weeks, and learned the hardway. They like to use [react-navigation](https://github.com/react-community/react-navigation) or [react-native-navigation](https://github.com/wix/react-native-navigation).

Although why is this component coupleed so tightly to the routing in the app? A video component should be free of this no? Just as the dependency is (react-native-video)?

**Comment by mostafa** [comment]
Added a new example that uses no special setup and does not use any routing/navigation and state management.

**Comment by Noitidart** [comment]
Oh wow so cool so simple. I didn't know it was that simple i though flux was required, thanks!!!
