### ISSUE TITLE
Full navigation bar android

### ISSUE THREAD

**Issue by Donhv** [mostafa/react-native-fullscreen-video#7]
How to really make full screen android. Navigation bar not hide

**Comment by mostafa** [comment]
Could you please explain it in detail?
Read the docs also.

**Comment by Donhv** [comment]
@mostafa 
https://raw.githubusercontent.com/mostafa/react-native-fullscreen-video/master/assets/demo.gif
Like demo. i want hide navigation bar in bottom when full screen

**Comment by mostafa** [comment]
This might help: https://github.com/mockingbot/react-native-immersive
And also this: https://developer.android.com/training/system-ui/immersive.html
