### ISSUE TITLE
Conflict with dependencies

### ISSUE THREAD

**Issue by GSolari79** [mostafa/react-native-fullscreen-video#9]
Using react-native-af-video-player at the same time causes the app to crash:

Tried to register two views with the same name RCTVideo

Exception thrown while executing UI block: *** -[NSURL initFileURLWithPath:]: nil string parameter

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1139
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
0x0

Is there a way to resolve this?

**Comment by mostafa** [comment]
As far as I see, `react-native-af-video-player` is a completely different package. Mine works on `react-native-video` and I have not tested it with other packages like the one you said!
